# Generated by Django 5.1.6 on 2025-03-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='subscription_tier',
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Default Customer Name', max_length=100),
        ),
    ]
