# Generated by Django 5.1.6 on 2025-03-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_customer_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='business_criticality',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low'), ('test', 'Test')], default='normal', max_length=20, verbose_name='Business Criticality'),
        ),
        migrations.AddField(
            model_name='asset',
            name='patch_cycle',
            field=models.PositiveIntegerField(default=30, verbose_name='Patch Cycle (days)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
