# Generated by Django 5.1.6 on 2025-03-03 10:55

from django.db import migrations

def add_default_customer_info(apps, schema_editor):
    Customer = apps.get_model('assets', 'Customer')
    for customer in Customer.objects.all():
        customer.display_name = "Customer A"
        customer.legal_name = "A real big company"
        customer.contact_person = "Mike Cunt"
        customer.save()

def reverse_default_customer_info(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_asset_business_criticality_asset_patch_cycle_and_more'),
    ]

    operations = [
        migrations.RunPython(add_default_customer_info, reverse_default_customer_info),
    ]
