# Generated by Django 5.1.6 on 2025-03-03 11:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_add_default_customer_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['display_name']},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(default='Mike Cunt', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='display_name',
            field=models.CharField(default='Customer A', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='legal_name',
            field=models.CharField(default='A real big company', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
